type Voiture = {
    "id" : number,
    "nom" : string, 
    "prenom" : string, 
    "datedenaissance" : DateTime,
    "tel" : string, 
    "email" : string, 
    "adresse" : string, 
    "cap" : string,
    "ville" : string,
    "modelevehicule" : string,
    "numeroclient" : string,
    "alimentation" : string,
    "typemotorisation" : string,
    "finition" : string,
    "dateimmat" : DateTime,
    "typepaiement" : string, 
    "datefinpaiement" : DateTime,
    "dateanniversairelivraison" : DateTime,
    "activeralerte" : boolean,
  }